### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by coderobt** [MarchRory/ai-judge-papers#68]
老这个有后端的代码嘛，运行起来登录不进去

**Comment by MarchRory** [comment]
负责后端和AI的同学不太想把代码开源

**Comment by coderobt** [comment]
好吧，谢谢哥&nbsp;


↘泪♂无声无息↖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月11日(星期二) 下午4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MarchRory/ai-judge-papers] 问题 (Issue #68)














 
负责后端和AI的同学不太想把代码开源
